"""Generate me/index.html (the personal copy) from index.html.

Run after editing index.html:  python3 tools/build_personal.py
The personal page loads the same files from the folder above via <base href="../">.
"""
from pathlib import Path

root = Path(__file__).resolve().parent.parent
html = (root / 'index.html').read_text()

swaps = [
    ('<meta charset="utf-8">', '<meta charset="utf-8">\n<base href="../">\n<meta name="si-app" content="me">'),
    ('<title>Skill Issue</title>', '<title>Skill Issue · PoppaGerbil</title>'),
    ('<meta name="apple-mobile-web-app-title" content="Skill Issue">', '<meta name="apple-mobile-web-app-title" content="Poppa SI">'),
    ('href="manifest.webmanifest"', 'href="me/manifest.webmanifest"'),
    ('href="icons/icon-192.png"', 'href="icons/me-192.png"'),
    ('href="icons/apple-touch-icon.png"', 'href="icons/me-apple-touch-icon.png"'),
]
for old, new in swaps:
    assert old in html, f'index.html changed; update tools/build_personal.py ({old})'
    html = html.replace(old, new, 1)

banner = '<!-- GENERATED by tools/build_personal.py from index.html. Edit index.html, then re-run. -->\n'
(root / 'me' / 'index.html').write_text(html.replace('<!doctype html>\n', '<!doctype html>\n' + banner, 1))
print('wrote me/index.html')
